import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import passwordResetRouter from "./password_reset";
import childrenRouter from "./children";
import screeningsRouter from "./screenings";
import appointmentsRouter from "./appointments";
import therapyPlansRouter from "./therapy_plans";
import reportsRouter from "./reports";
import dashboardRouter from "./dashboard";
import videoAnalysisRouter from "./video_analysis";
import availabilityRouter from "./availability";
import specialtyFeesRouter from "./specialty_fees";
import paymentsRouter from "./payments";
import rescheduleRouter from "./reschedule";
import billingRouter from "./billing";
import aiAnalysisRouter from "./ai_analysis_results";
import auditLogsRouter from "./audit_logs";
import therapySessionNotesRouter from "./therapy_session_notes";
import developmentalMilestonesRouter from "./developmental_milestones";
import riskHistoryRouter from "./risk_history";
import screeningResponsesRouter from "./screening_responses";
import documentsRouter from "./documents";
import ticketsRouter from "./tickets";
import consentsRouter from "./consents";
import notificationsRouter from "./notifications";
import featureFlagsRouter from "./feature_flags";
import brainGymRouter from "./brain_gym";
import intakeFormsRouter from "./intake_forms";
import queueRouter from "./queue";
import soapNotesRouter from "./soap_notes";
import schoolClassesRouter from "./school_classes";
import observationsRouter from "./observations";
import iepPlansRouter from "./iep_plans";
import interventionsRouter from "./interventions";
import healthProgramsRouter from "./health_programs";
import messagingRouter from "./messaging";
import communityRouter from "./community";
import otpRouter from "./otp";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(passwordResetRouter);
router.use(childrenRouter);
router.use(screeningsRouter);
router.use(appointmentsRouter);
router.use(availabilityRouter);
router.use(specialtyFeesRouter);
router.use(paymentsRouter);
router.use(rescheduleRouter);
router.use(therapyPlansRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(videoAnalysisRouter);
router.use(billingRouter);
router.use(aiAnalysisRouter);
router.use(auditLogsRouter);
router.use(therapySessionNotesRouter);
router.use(developmentalMilestonesRouter);
router.use(riskHistoryRouter);
router.use(screeningResponsesRouter);
router.use(documentsRouter);
router.use(ticketsRouter);
router.use(consentsRouter);
router.use(notificationsRouter);
router.use(featureFlagsRouter);
router.use(brainGymRouter);
router.use(intakeFormsRouter);
router.use(queueRouter);
router.use(soapNotesRouter);
router.use(schoolClassesRouter);
router.use(observationsRouter);
router.use(iepPlansRouter);
router.use(interventionsRouter);
router.use(healthProgramsRouter);
router.use(messagingRouter);
router.use(communityRouter);
router.use(otpRouter);
router.use(adminRouter);

export default router;
