import { router as workflowRouter } from "./workflow";
import "./workflow-care";
import "./workflow-payments";
import "./workflow-files";
import {Router,type IRouter} from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import passwordResetRouter from "./password_reset";
import otpRouter from "./otp";
const router:IRouter=Router();
router.use(workflowRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(passwordResetRouter);
router.use(otpRouter);
export default router;
